stages:
  process_data:
    cmd: python src/process_data.py
    deps:
    - data/raw
    - src/process_data.py
    - config/main.yaml
    - config/process
    outs:
    - data/intermediate
  train:
    cmd: python src/segment.py
    deps:
    - data/intermediate
    - src/segment.py
    - config/main.yaml
    outs:
    - data/final
    - model/cluster.pkl