name: Run pipeline
on:
  push:
    branches:
     - main
    paths:
      - config/**
      - src/**
      - data/*
      - .github/workflows/run_pipeline.yaml
jobs:
  run_pipeline:
    name: Run pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current repository
        id: checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Pull data from DVC
        run: uv run dvc pull

      - name: Run the pipeline with DVC
        run: uv run dvc repro

      - name: Push the outcomes to DVC remote storage
        run: uv run dvc push

      - name: Commit changes in dvc.lock
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes in dvc.lock
          branch: main
          file_pattern: dvc.lock